sudo: required
services:
    - docker

before_install:
    - docker build -t ausarthevile/docker-react -f Dockerfile.dev .

script:
    - docker run ausarthevile/docker-react npm run test -- --coverage